AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  LambdaExecutionRoleArn:
    Description: Lambda role Arn
    Type: String
    Default: arn:aws:iam::xxxxxxxxxx:role/LambdaRole
  Image:
    Description: Container image uri
    Type: String
    Default: xxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/image_name:latest
  Environment:
    Description: Execution environment
    Type: String
    AllowedValues:
      - production
    Default: production
  Port:
    Description: Container port
    Type: String
    Default: 3002
  RdsDbUrl:
    Description: RDS url
    Type: String
Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      PackageType: Image
      Role: !Ref "LambdaExecutionRoleArn"
      Code:
        ImageUri: !Ref "Image"
      Architectures:
        - x86_64
      MemorySize: 1024
      Timeout: 300
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          PORT: !Ref Port
          RDS_DB: !Ref RdsDbUrl
